<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-25T17:00:02 IST" name="Default suite" finished-at="2022-12-25T17:04:29 IST" duration-ms="267101">
    <groups>
    </groups>
    <test started-at="2022-12-25T17:00:02 IST" name="Default test" finished-at="2022-12-25T17:04:29 IST" duration-ms="267101">
      <class name="test.AutomationPizza.AppTest">
        <test-method is-config="true" signature="startReport()[pri:0, instance:test.AutomationPizza.AppTest@2794eab6]" started-at="2022-12-25T17:00:02 IST" name="startReport" finished-at="2022-12-25T17:00:02 IST" duration-ms="205" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startReport -->
        <test-method is-config="true" signature="setup()[pri:0, instance:test.AutomationPizza.AppTest@2794eab6]" started-at="2022-12-25T17:00:02 IST" name="setup" finished-at="2022-12-25T17:00:04 IST" duration-ms="2514" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="OpenHomePage()[pri:0, instance:test.AutomationPizza.AppTest@2794eab6]" started-at="2022-12-25T17:00:04 IST" name="OpenHomePage" finished-at="2022-12-25T17:04:28 IST" duration-ms="263773" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Yes I am! Did I have you fooled?] but found [I certainly am. I can respond like a human but more efficiently.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Yes I am! Did I have you fooled?] but found [I certainly am. I can respond like a human but more efficiently.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at test.AutomationPizza.AppTest.OpenHomePage(AppTest.java:335)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- OpenHomePage -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:test.AutomationPizza.AppTest@2794eab6]" started-at="2022-12-25T17:04:28 IST" name="getResult" finished-at="2022-12-25T17:04:28 IST" duration-ms="332" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=OpenHomePage status=FAILURE method=AppTest.OpenHomePage()[pri:0, instance:test.AutomationPizza.AppTest@2794eab6] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="endReport()[pri:0, instance:test.AutomationPizza.AppTest@2794eab6]" started-at="2022-12-25T17:04:28 IST" name="endReport" finished-at="2022-12-25T17:04:29 IST" duration-ms="245" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endReport -->
      </class> <!-- test.AutomationPizza.AppTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
